# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
